name: Refresh Instahyre Resume

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/2 * * * *'

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Triggered by ${{ github.event_name }}"
